language: node_js
node_js:
  - "node"
  - "10"
  - "8"
cache:
  directories:
    - node_modules
script:
  - npm test
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
